services:
  db:
    image: postgres:15-alpine
    container_name: checkfood-db
    restart: always
    # Načtení proměnných ze specifického souboru
    env_file:
      - .env.local
    environment:
      # Zde zůstávají klíče, které Postgres očekává,
      # hodnoty se vezmou z .env.example.local
      POSTGRES_DB: checkfood
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d checkfood"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - checkfood-network

volumes:
  postgres_data:

networks:
  checkfood-network:
    driver: bridge