services:
  postgres:
    image: postgres:16
    container_name: checkfood-postgres
    restart: unless-stopped

    env_file:
      - .env.local

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: Europe/Prague

    ports:
      - "${POSTGRES_PORT}:5432"

    volumes:
      - checkfood_pgdata:/var/lib/postgresql/data

volumes:
  checkfood_pgdata:
